apiVersion: v1
kind: Namespace
metadata:
  name: todo-app
  labels:
    app: todo-app
---
kind: Service
apiVersion: v1
metadata:
  name: todo-app
  namespace: todo-app
  labels:
    app: todo-app
spec:
  selector:
    app: todo-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  namespace: todo-app
  labels:
    app: todo-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - name: todo-app
        image: rohitjm/todo-app:406d8e0aa6408887656787bebd0067aa3dddfcb2
        ports:
        - containerPort: 3000
