apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  labels:
    app: todo-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
        - name: todo-app
          imagePullPolicy: IfNotPresent
          image: rohitjm/todo-app:406d8e0aa6408887656787bebd0067aa3dddfcb2
